layout: default
title: Data By Jerrica
subtitle: Smarter Benefits, Better Business Decisions
Description: Data by Jerrica delivers analytics that simplify compliance, streamline workflows, and empower businesses owners with clear and actionable conclusions.
remote_theme: mmistakes/minimal-mistakes
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

sass:
  sass_dir: _sass
  style: compressed

minimal_mistakes_skin: default
