title: Emerald Healing Arts
subtitle: A Gentle Approach to Deep Healing
description: Emerald Healing Arts encourages transformation through healing touch and education in the touch therapy community.
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

sass:
  sass_dir: _sass
  style: compressed

